// Canonical IoM domain types — the single source, re-exported from io2p-client. Migrated code imports
// from here, not from 'iom-sdk' (dormant) or 'io2p-client' directly.

export type UUID = string

export type {
  ObjectDTO,
  ProcessDTO,
  TemplateDTO,
  FormulaDTO,
  ConstantDTO,
  FileDTO,
  UserDTO,
  UserSummaryDTO,
  GrantDTO,
  GrantResponse,
  ShareDTO,
  SharedByMeItem,
  RevokeResult,
  LivenessDTO,
  ReadinessDTO,
  ProblemDetails,
  CreateObjectResponse,
  UpdateObjectBody,
  CreateProcessResponse,
  UpdateProcessBody,
  UpdateTemplateBody,
  CreateFormulaBody,
  CreateConstantBody,
  AppendConstantVersionBody,
  CreateShareBody,
  UpdateShareBody,
  GrantBody,
  RevokeBody,
  ObjectListQuery,
  ProcessListQuery,
  InitUploadBody,
  InitUploadResponse,
  CompleteBody,
  CompleteResponse,
  SignedUrlResponse,
  FileTarget,
  CreateObjectInput,
  CreateProcessInput,
  CreateTemplateInput,
  ValueInput,
  PropertyInput,
  CalcInput,
  CalcArgInput,
  FileInput,
  ListObjectsQuery,
  ListProcessesQuery,
  ListTemplatesQuery,
  ListFormulasQuery,
  ListConstantsQuery,
  ListFilesQuery,
  ListSharesQuery,
  ListUsersQuery,
  Page,
} from 'io2p-client'

// Error classes re-exported as VALUES (runtime `instanceof`), not `export type`.
export {
  IomError,
  ValidationError,
  ConflictError,
  PreconditionFailedError,
  NotFoundError,
  ForbiddenError,
  UnauthorizedError,
  mapProblemToError,
} from 'io2p-client'
